# Generated by Django 3.0 on 2020-02-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimespamtedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('timespamtedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite1.TimespamtedModel')),
                ('titre_gal', models.CharField(max_length=255)),
                ('description_gal', models.TextField()),
            ],
            bases=('mysite1.timespamtedmodel',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('timespamtedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite1.TimespamtedModel')),
                ('titre_img', models.CharField(max_length=255)),
                ('description_gal', models.TextField()),
                ('galerie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.Galerie')),
            ],
            bases=('mysite1.timespamtedmodel',),
        ),
    ]
