# Generated by Django 3.0.3 on 2020-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie',
            name='image_gal',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
