# Generated by Django 3.0 on 2020-02-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0002_galerie_image_timespamtedmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='galerie_id',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='description_gal',
            new_name='description_img',
        ),
    ]
