# Generated by Django 3.0.3 on 2020-02-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0002_galerie_image_gal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galerie',
            name='image_gal',
        ),
    ]
