# Generated by Django 3.0.3 on 2020-02-23 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0004_image_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('timespamtedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mysite1.TimespamtedModel')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('gal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite1.Galerie')),
            ],
            bases=('mysite1.timespamtedmodel',),
        ),
    ]
