# Generated by Django 3.0.3 on 2020-02-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite1', '0005_commentaire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commentaire',
            new_name='Comment',
        ),
    ]
